### PR TITLE
Use updated links on doc pages

### PR DESCRIPTION
**Pull request by ChrisMaddock**
Trivial - I just wanted to get rid of the redirect page here. 🙂

### CODE REVIEW

**Comment by jnm2** [comment]
Oh right, next time I'll merge.

**Comment by ChrisMaddock** [comment]
I presumed this was fine, being simple and reviewed by one other team member.

For the sake of process, what was the reason you didn't merge it, @jnm2? 🙂

**Comment by jnm2** [comment]
@ChrisMaddock I simply forgot. I was supposed to be the one to merge. 😀

**Comment by jnm2** [comment]
But it's totally fine that you merged since I didn't.

**Pull request merged**
