### PR TITLE
update Gemfile

### PR DESCRIPTION
**Pull request by Arhell**
resolve https://github.com/nunit/nunit.github.io/issues/149

### CODE REVIEW

**Comment by SeanKilleen** [comment]
From the build log on this:

>5:26:21 PM: Because github-pages >= 228 depends on jekyll = 3.9.3
> 5:26:21 PM:   and Gemfile depends on jekyll >= 3.9.4,
> 5:26:21 PM:   github-pages >= 228 cannot be used.
> 5:26:21 PM: So, because Gemfile depends on github-pages ~> 228,
> 5:26:21 PM:   version solving has failed.

You can see the dependency versions at https://pages.github.com/versions/

**Comment by Arhell** [comment]
> From the build log on this:
> 
> > 5:26:21 PM: Because github-pages >= 228 depends on jekyll = 3.9.3
> > 5:26:21 PM:   and Gemfile depends on jekyll >= 3.9.4,
> > 5:26:21 PM:   github-pages >= 228 cannot be used.
> > 5:26:21 PM: So, because Gemfile depends on github-pages ~> 228,
> > 5:26:21 PM:   version solving has failed.
> 
> You can see the dependency versions at https://pages.github.com/versions/

Thanks, I know that's why Draft mode

**Review by Arhell — COMMENTED** [review]
update

**Comment by Arhell** [comment]
@SeanKilleen  take a look please

**Pull request merged**
