### PR TITLE
Import Legacy Documentation

### LINKED ISSUE #4: Import legacy documentation
This could be experimental, but can we pull in the legacy document partials and then write an index.php that uses Javascript to load the docs? Will index.php be treated as html on github.io?

### LINKED ISSUE #15: Update copyright
The copyright is now to NUnit, switch to CC and put under @CharliePoole and @rprouse.

For CC, I would prefer Attribution-NonCommercial-ShareAlike so people can't turn the docs into a commercial book without the copyright holders' permissions. Sound good?

### PR DESCRIPTION
**Pull request by rprouse**
Fixes #4 
Fixes #15 

This imports the legacy documentation. Currently, if you go to the old documentation URI, it will redirect you using Javascript to the new URI. Tons of files, but most are just the old documentation.

The docs are now wrapped in the new site, but maintain most of their original formatting and menus. The only thing that I haven't been able to get working is the language switching dropdowns. I have the JS and CSS for them, but they aren't working. I think that is lower priority, so I am fine to look at it later.

I also updated the copyright to CC.

Here are a few screenshots,

image

image

image

### CODE REVIEW

**Comment by rprouse** [comment]
This is hard to review because of the size. Looking at the diffs keeps locking up my browser. If the @nunit/core-team wants, we can merge so that you can review the website and we can update from there is smaller commits. I think that would be okay this time since the site isn't live yet, but I will leave that up to another team member 😄

**Comment by CharliePoole** [comment]
I think you should merge. It would be much easier to review the site than review diffs, because we are not familiar with the source of the site, but we all know what we like when we see it. 😸

**Comment by rprouse** [comment]
@CharliePoole I agree, merging. You should be able to view after a few minutes. It takes 11 seconds to build on my machine, it may take longer on GitHub. http://nunit.github.io

You may also have to refresh since I updated CSS and JS.

**Comment by rprouse** [comment]
It took a few minutes and a refresh was needed, but the docs and other changes are now live for your viewing pleasure.

**Comment by ChrisMaddock** [comment]
This looks to have worked out perfectly - the link redirection is great! Nice job. 😄

**Pull request merged**
