### PR TITLE
Remove language pickers in legacy docs

### LINKED ISSUE #18: Legacy Docs: Language picker broken
image

We can just strip them all out - the code samples look find just one under each other.

### PR DESCRIPTION
**Pull request by ChrisMaddock**
Fixes #18

### CODE REVIEW

**Comment by rprouse** [comment]
Looks good, but you should also delete `codefuncs.js`, remove it from the help template and remove the related CSS from `main.scss`

**Comment by ChrisMaddock** [comment]
Hopefully that covers all references? Broken into commits so you can see what I've done.

**Comment by CharliePoole** [comment]
I was planning to fix rather than remove, but this works too.

**Comment by ChrisMaddock** [comment]
I'd have no problem with someone fixing it instead. 😄 

I just went for the easy option, given these are all legacy pages. If you'd prefer to do so, please go ahead!

**Comment by rprouse** [comment]
I am fine with fixing or with dropping. These are legacy docs, so I wouldn't want to spend too much time. We could also do a series of search and replaces on `<pre class="highlight" id="CS1"` and add a little language header above each code block.

@CharliePoole if you want to try to fix this, let us know, otherwise we can merge.

**Comment by CharliePoole** [comment]
I should have commented sooner. IMO, we shouldn't try to fix anything in the legacy docs until the more general issue of the `nunit.css` not working (#17) is fixed. It seems possible that some of these problems will go away once that is done.

@rprouse Can you tell us how you want this repository worked on by others? If I understand correctly, we can only preview the effect of changes if we install jekyll in a local server. Correct? Code-wise, this stuff could be an easy fix but I'm not comfortable changing a website if I can't actually see the results before they go live. The integration in a repo makes it easy to change things and to review the code, but AFAICS not the appearance.

**Comment by jnm2** [comment]
Would be cool to have a CI server that publishes the website to a unique subdomain for every PR.

**Comment by jnm2** [comment]
^ Also very dangerous if you don't trust the author. Would need a whitelist.

**Comment by rprouse** [comment]
@CharliePoole yes, you need ruby installed to preview the website locally. The instructions in the README should get people up and running. Once everything is installed, the `jekyll serve` is the only command you need. It will compile everything and serve it on a localhost port then watch for file changes and automatically recompile. The mass of legacy help docs makes compiles longer than they should be (11 secs), but it is manageable.

**Comment by CharliePoole** [comment]
Looks like you have to install Jekyll as well - not surprisingly. :smile:

I didn't realize Jekyll was it's own server. That simplifies for those without a web server installed.

It seems to me that you should be able to avoid regenerating the legacy docs once you get them right.

I've been assuming that the global fix needed by #17 is something you would prefer to do, since it goes back to the original conversion. At a minimum, if somebody else is doing it, I suggest you tell them how you want it done, since it's part of the site architecture. I can reconvert docs for you with different parameters if that would help. I can even do it on my laptop here in Paris.

**Comment by rprouse** [comment]
@CharliePoole yes, Jekyll is installed as part of the `bundle install`, it is in the `gemfile`. It would be cool if it could stop watching the doc files. The other idea I had was to add back in the concept of the PHP not changed since, but I am not sure how to do it at this point.

For the global fix for #17, I pulled in most of `nunit.css` into the `main.sass` file. It probably just needs some adjustment for the wrapping containers and an update for the `help_content` change. There may be additional CSS that needs to be pulled in, but I didn't want to pull more in than was needed.

**Comment by rprouse** [comment]
I managed to get the language pickers working tonight, so we can close this. PR will follow.

**Pull request closed without merging**
